### ISSUE TITLE
Header & footer

### ISSUE THREAD

**Issue by Patais** [jeje-01350/projet-versioning#2]
Réaliser le footer et header afin qu'ils soient utilisés dans l'ensemble des pages

**Comment by jeje-01350** [comment]
@Patais pk pas faire une sorte de composant

**Comment by mathisrome** [comment]
@jeje-01350 On peut faire en composant mais dans tous les cas c'est un one page donc pas forcément utile

**Comment by jeje-01350** [comment]
@mathisrome pas faux loan m'a induit en erreur avec son message
